#if !canImport(ObjectiveC)
import XCTest

extension HexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HexTests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HexTests.__allTests__HexTests),
    ]
}
#endif
