#if !canImport(ObjectiveC)
import XCTest

extension Base64Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base64Tests = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base64Tests.__allTests__Base64Tests),
    ]
}
#endif
